declare namespace NodeJS {
  interface ProcessEnv {
    REACT_APP_MONGO_DB_USER: string;
    REACT_APP_MONGO_DB_PASSWORD: string;
    REACT_APP_MONGO_DB_USER: string;
    REACT_APP_MONGO_DB_PASSWORD: string;
    REACT_APP_FIREBASE_API_KEY: string;
    REACT_APP_FIREBASE_AUTH_DOM: string;
    REACT_APP_FIREBASE_PROJECT_ID: string;
    REACT_APP_FIREBASE_STORAGE_BUCKET: string;
    REACT_APP_FIREBASE_MESSAGIN_SENDER_ID: string;
    REACT_APP_FIREBASE_APP_ID: string;
  }
}
